=== CreatorBeastGD/pokemon-go-api/data/raidOverwrites.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="root" type="rootType"/>
    <xs:complexType name="startDateType">
        <xs:sequence>
            <xs:element type="xs:string" name="date"/>
            <xs:element type="xs:string" minOccurs="0" name="timezone"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="endDateType">
        <xs:sequence>
            <xs:element type="xs:string" name="date"/>
            <xs:element type="xs:string" minOccurs="0" name="timezone"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="raidbossType">
        <xs:sequence>
            <xs:element type="startDateType" name="startDate"/>
            <xs:element type="endDateType" name="endDate"/>
            <xs:element type="xs:string" name="pokemon"/>
            <xs:element type="xs:string" minOccurs="0" name="form"/>
            <xs:element type="xs:string" name="level"/>
            <xs:element type="xs:boolean" name="shiny"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="rootType">
        <xs:sequence>
            <xs:element type="raidbossType" name="raidboss" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== CreatorBeastGD/pokemon-go-api/data/raidOverwrites.xml
<?xml version="1.0" encoding="UTF-8" ?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="raidOverwrites.xsd">
    <raidboss>
        <startDate>
            <date>2021-01-01 09:00:00</date>
            <timezone>UTC</timezone>
        </startDate>
        <endDate>
            <date>2021-01-01 21:00:00</date>
            <timezone>UTC</timezone>
        </endDate>
        <pokemon>KYUREM</pokemon>
        <level>lvl5</level>
        <shiny>false</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-01-01 21:00:00</date>
            <timezone>UTC</timezone>
        </startDate>
        <endDate>
            <date>2021-01-05 10:00:00</date>
        </endDate>
        <pokemon>HO_OH</pokemon>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-01-05 10:00:00</date>
        </startDate>
        <endDate>
            <date>2021-01-12 10:00:00</date>
        </endDate>
        <pokemon>GENESECT</pokemon>
        <form>GENESECT_BURN</form>
        <level>lvl5</level>
        <shiny>false</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-01-12 10:00:00</date>
        </startDate>
        <endDate>
            <date>2021-01-19 10:00:00</date>
        </endDate>
        <pokemon>HEATRAN</pokemon>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-01-19 10:00:00</date>
        </startDate>
        <endDate>
            <date>2021-01-26 10:00:00</date>
        </endDate>
        <pokemon>KYOGRE</pokemon>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-01-19 10:00:00</date>
        </startDate>
        <endDate>
            <date>2021-01-26 10:00:00</date>
        </endDate>
        <pokemon>GROUDON</pokemon>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-01-26 10:00:00</date>
        </startDate>
        <endDate>
            <date>2021-01-31 10:00:00</date>
        </endDate>
        <pokemon>ENTEI</pokemon>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-01-31 10:00:00</date>
        </startDate>
        <endDate>
            <date>2021-02-04 10:00:00</date>
        </endDate>
        <pokemon>RAIKOU</pokemon>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-02-04 10:00:00</date>
        </startDate>
        <endDate>
            <date>2021-02-09 10:00:00</date>
        </endDate>
        <pokemon>SUICUNE</pokemon>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-02-09 10:00:00</date>
        </startDate>
        <endDate>
            <date>2021-02-20 09:00:00</date>
        </endDate>
        <pokemon>LATIAS</pokemon>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-02-09 10:00:00</date>
        </startDate>
        <endDate>
            <date>2021-02-20 09:00:00</date>
        </endDate>
        <pokemon>LATIOS</pokemon>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-02-20 09:00:00</date>
        </startDate>
        <endDate>
            <date>2021-03-01 08:00:00</date>
        </endDate>
        <pokemon>ARTICUNO</pokemon>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-02-20 09:00:00</date>
        </startDate>
        <endDate>
            <date>2021-03-01 08:00:00</date>
        </endDate>
        <pokemon>ZAPDOS</pokemon>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-02-20 09:00:00</date>
        </startDate>
        <endDate>
            <date>2021-03-01 08:00:00</date>
        </endDate>
        <pokemon>MOLTRES</pokemon>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-02-20 09:00:00</date>
        </startDate>
        <endDate>
            <date>2021-03-01 08:00:00</date>
        </endDate>
        <pokemon>MEWTWO</pokemon>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-03-01 08:00:00</date>
        </startDate>
        <endDate>
            <date>2021-03-06 08:00:00</date>
        </endDate>
        <pokemon>LANDORUS</pokemon>
        <form>LANDORUS_INCARNATE</form>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-03-06 08:00:00</date>
        </startDate>
        <endDate>
            <date>2021-03-11 08:00:00</date>
        </endDate>
        <pokemon>TORNADUS</pokemon>
        <form>TORNADUS_INCARNATE</form>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-03-11 08:00:00</date>
        </startDate>
        <endDate>
            <date>2021-03-16 10:00:00</date>
        </endDate>
        <pokemon>THUNDURUS</pokemon>
        <form>THUNDURUS_INCARNATE</form>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-03-16 10:00:00</date>
        </startDate>
        <endDate>
            <date>2021-03-30 10:00:00</date>
        </endDate>
        <pokemon>THUNDURUS</pokemon>
        <form>THUNDURUS_THERIAN</form>
        <level>lvl5</level>
        <shiny>false</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-03-27 10:00:00</date>
        </startDate>
        <endDate>
            <date>2021-03-28 20:00:00</date>
        </endDate>
        <pokemon>RAYQUAZA</pokemon>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-03-30 10:00:00</date>
        </startDate>
        <endDate>
            <date>2021-04-13 10:00:00</date>
        </endDate>
        <pokemon>TORNADUS</pokemon>
        <form>TORNADUS_THERIAN</form>
        <level>lvl5</level>
        <shiny>false</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-04-13 10:00:00</date>
        </startDate>
        <endDate>
            <date>2021-04-27 10:00:00</date>
        </endDate>
        <pokemon>LANDORUS</pokemon>
        <form>LANDORUS_THERIAN</form>
        <level>lvl5</level>
        <shiny>false</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-04-27 10:00:00</date>
        </startDate>
        <endDate>
            <date>2021-05-04 10:00:00</date>
        </endDate>
        <pokemon>LANDORUS</pokemon>
        <form>LANDORUS_INCARNATE</form>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-04-27 10:00:00</date>
        </startDate>
        <endDate>
            <date>2021-05-04 10:00:00</date>
        </endDate>
        <pokemon>TORNADUS</pokemon>
        <form>TORNADUS_INCARNATE</form>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-04-27 10:00:00</date>
        </startDate>
        <endDate>
            <date>2021-05-04 10:00:00</date>
        </endDate>
        <pokemon>THUNDURUS</pokemon>
        <form>THUNDURUS_INCARNATE</form>
        <level>lvl5</level>
        <shiny>true</shiny>
    </raidboss>
    <!-- may-2021-events -->
    <raidboss>
        <startDate>
            <date>2021-05-04 10:00:00</date>
        </startDate>
        <endDate>
            <date>2021-05-18 10:00:00</date>
        </endDate>
        <pokemon>XERNEAS</pokemon>
        <level>lvl5</level>
        <shiny>false</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-05-18 10:00:00</date>
        </startDate>
        <endDate>
            <date>2021-06-01 10:00:00</date>
        </endDate>
        <pokemon>YVELTAL</pokemon>
        <level>lvl5</level>
        <shiny>false</shiny>
    </raidboss>
    <raidboss>
        <startDate>
            <date>2021-05-15 17:00:00</date>
        </startDate>
        <endDate>
            <date>2021-06-01 10:00:00</date>
        </endDate>
        <pokemon>ALTARIA</pokemon>
        <form>ALTARIA_MEGA</form>
        <level>mega</level>
        <shiny>false</shiny>
    </raidboss>

</root>
